#ssh各协议能够防范的攻击方式
协商密钥：攻击者使用fiddler同时截获到密钥和加密数据，从而解密出明文的账号密码
校验服务器：攻击者使用fiddler伪造了一个钓鱼页面，给用户电脑植入病毒
加密数据：攻击者使用fiddler直接截获到明文的账号密码
校验数据完整性：攻击者使用fiddler修改了响应，给用户造成误导性行为
压缩数据：暂无攻击方式
#ssh各协议的属性名
协商密钥：KexAlgorithms
校验服务器：HostKeyAlgorithms
加密数据：Ciphers
校验数据完整性：MACs
压缩数据：CompressionAlgorithms
#ssh各协议常见属性值
协商密钥：diffie-hellman/curve/dh/c
校验服务器：ssh/ds/rsa
加密数据：aes/chacha
校验数据完整性：mac
压缩数据：zlib